# Generated by Django 4.1.6 on 2023-04-11 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
    ]
