# Generated by Django 4.1.6 on 2023-04-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_application_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='client_phone_number',
            field=models.IntegerField(max_length=50),
        ),
    ]
