# Generated by Django 4.1.6 on 2023-04-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_application_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='client_phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
