# Generated by Django 4.1.6 on 2023-04-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_application_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='client_name',
            field=models.CharField(max_length=255, verbose_name='Ismingiz'),
        ),
        migrations.AlterField(
            model_name='application',
            name='client_phone_number',
            field=models.CharField(max_length=50, verbose_name='Telefon nomer'),
        ),
    ]
